### ISSUE TITLE
GPSA

### ISSUE THREAD

**Issue by COMPLEXI1** [maiziezhoulab/BenchmarkST#2]
Hello, I have a question regarding the GPSA registration method. Currently, I am using the GPSA de novo approach for pairwise registration of the STARMAP data, but I am not achieving satisfactory results. Based on your results of GPSA on the DLPFC dataset, have you encountered similar issues?

**Comment by OliiverHu** [comment]
Hi! As you can see from our paper, there is no GPSA related results for the MERFISH mouse hypothalamus. I believe STARMAP data could experience the same issues as we did with MERFISH. But personally, it is still worth asking the contributors of GPSA for possible suggestions: https://github.com/andrewcharlesjones/spatial-alignment 

Let me know if you have further questions.
